package autodoctor

import (
	"time"
)

// Severity represents the criticality level of an identified issue.
type Severity string

const (
	SeverityCritical Severity = "CRITICAL"
	SeverityWarning  Severity = "WARNING"
	SeverityInfo     Severity = "INFO"
	SeverityOK       Severity = "OK"
)

// IssueCategory classifies the area of the finding.
type IssueCategory string

const (
	CategoryContainer IssueCategory = "Contenedor"
	CategoryStorage   IssueCategory = "Almacenamiento"
	CategorySecurity  IssueCategory = "Seguridad"
	CategoryHost      IssueCategory = "Sistema Host"
)

// Issue represents an actionable finding with root cause analysis.
type Issue struct {
	ID                 string        `json:"id"`
	Category           IssueCategory `json:"category"`
	Severity           Severity      `json:"severity"`
	Title              string        `json:"title"`
	Target             string        `json:"target"`
	Description        string        `json:"description"`
	RootCause          string        `json:"root_cause"`
	Recommendation     string        `json:"recommendation"`
	RemediationCommand string        `json:"remediation_cmd,omitempty"`
	Timestamp          time.Time     `json:"timestamp"`
}

// SubsystemStatus represents the health overview of a component.
type SubsystemStatus struct {
	Name    string   `json:"name"`
	Status  Severity `json:"status"`
	Summary string   `json:"summary"`
}

// StorageAudit summarizes Docker disk footprint and reclaimable data.
type StorageAudit struct {
	ImagesTotalBytes      int64  `json:"images_total_bytes"`
	ImagesReclaimable     int64  `json:"images_reclaimable"`
	ImagesCount           int    `json:"images_count"`
	DanglingImagesCount   int    `json:"dangling_images_count"`
	VolumesTotalBytes     int64  `json:"volumes_total_bytes"`
	VolumesReclaimable    int64  `json:"volumes_reclaimable"`
	VolumesCount          int    `json:"volumes_count"`
	OrphanedVolumesCount  int    `json:"orphaned_volumes_count"`
	BuildCacheTotal       int64  `json:"build_cache_total"`
	BuildCacheReclaimable int64  `json:"build_cache_reclaimable"`
	TotalReclaimableBytes int64  `json:"total_reclaimable_bytes"`
	TotalDockerBytes      int64  `json:"total_docker_bytes"`
}

// HealthReport is the aggregated diagnosis generated by AutoDoctor.
type HealthReport struct {
	HealthScore       int               `json:"health_score"` // 0 - 100
	HealthLabel       string            `json:"health_label"`
	HealthBadge       string            `json:"health_badge"`
	Subsystems        []SubsystemStatus `json:"subsystems"`
	Issues            []Issue           `json:"issues"`
	TopActions        []Issue           `json:"top_actions"` // Top 3 prioritized
	Storage           StorageAudit      `json:"storage"`
	ContainersRunning int               `json:"containers_running"`
	ContainersStopped int               `json:"containers_stopped"`
	ContainersTotal   int               `json:"containers_total"`
	GeneratedAt       time.Time         `json:"generated_at"`
}
